import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";

const robotoFont = Roboto({
	variable: "--font-roboto",
});

const robotoMonoFont = Roboto_Mono({
	variable: "--font-roboto-mono",
});


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
			</head>
			<body className={`${robotoFont.variable} ${robotoMonoFont.variable} antialiased`}>{children}</body>
		</html>
	);
}
